### ISSUE TITLE
AAEmu.Editor SKU generation throwing null object ref when no items exist.

### ISSUE THREAD

**Issue by Noitabara** [ZeromusXYZ/AAEmu-Tools#8]
Hello! It seems when there are no SKU's present and the form has to generate one, the refrence to what i assume is supposed to be the does not seem to exist.

![AAEmu DBEditor_AG63dYuIOc](https://github.com/ZeromusXYZ/AAEmu-Tools/assets/5560528/cb02667f-e487-4919-bd5c-0da691654256)
![AAEmu DBEditor_UNdutGoJCB](https://github.com/ZeromusXYZ/AAEmu-Tools/assets/5560528/d0a2b108-cfd1-4504-beab-04d3c8be9eed)

suspected function in question
```
private void btnSKUGetNewId_Click(object sender, EventArgs e)
        {
            var lastSku = Data.MySqlDb.Game.IcsSkus.OrderBy(x => x.Sku).Reverse().FirstOrDefault();
            if (lastSku == null)
            {
                tSKUSKU.Text = "1000000";
            }
            tSKUSKU.Text = (lastSku.Sku + 1).ToString();
        }
```

stack trace

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AAEmu.DBEditor.forms.server.ICSForm.btnSKUGetNewId_Click(Object sender, EventArgs e) in D:\Dev\GitHub\ZeromusXYZ\AAEmu-Tools\AAEmu.DBEditor\forms\server\ICSForm.cs:line 552
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Private.CoreLib.dll
----------------------------------------
AAEmu.DBEditor
    Assembly Version: 0.0.1.1
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\AAEmu.DBEditor.dll
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Numerics.Vectors.dll
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Memory.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Loader.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.ObjectModel.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\System.Drawing.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Collections.NonGeneric.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.3\System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Private.Uri.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Security.Cryptography.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Xml.XmlSerializer.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Linq.Expressions.dll
----------------------------------------
Microsoft.EntityFrameworkCore
    Assembly Version: 7.0.11.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.EntityFrameworkCore.dll
----------------------------------------
System.Linq.Queryable
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Linq.Queryable.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Collections.Immutable.dll
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Linq.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.DependencyInjection.Abstractions.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.Tracing.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.DependencyInjection.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
Microsoft.EntityFrameworkCore.Abstractions
    Assembly Version: 7.0.11.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.EntityFrameworkCore.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Caching.Abstractions.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.ThreadPool.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
MySql.Data
    Assembly Version: 8.0.33.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\MySql.Data.dll
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Data.Common.dll
----------------------------------------
Pomelo.EntityFrameworkCore.MySql
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Pomelo.EntityFrameworkCore.MySql.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Text.RegularExpressions.dll
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Assembly Version: 7.0.11.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.EntityFrameworkCore.Relational.dll
----------------------------------------
MySqlConnector
    Assembly Version: 2.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\MySqlConnector.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Configuration.Abstractions.dll
----------------------------------------
System.Transactions.Local
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Transactions.Local.dll
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Logging.dll
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Options.dll
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Caching.Memory.dll
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 7.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Extensions.Primitives.dll
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.ComponentModel.Annotations.dll
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Text.Json.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Intrinsics.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Net.Primitives.dll
----------------------------------------
System.Net.Security
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Net.Security.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Net.NameResolution.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Security.Claims.dll
----------------------------------------
Microsoft.Data.Sqlite
    Assembly Version: 7.0.11.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.Data.Sqlite.dll
----------------------------------------
AAPacker
    Assembly Version: 1.0.1.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\AAPacker.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Security.Cryptography.Primitives.dll
----------------------------------------
BitmapUtil
    Assembly Version: 1.0.0.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\BitmapUtil.dll
----------------------------------------
Pfim
    Assembly Version: 0.11.2.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Pfim.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\netstandard.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Numerics.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Metadata.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.IO.MemoryMappedFiles.dll
----------------------------------------
SQLitePCLRaw.core
    Assembly Version: 2.1.4.1835
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\SQLitePCLRaw.core.dll
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly Version: 2.1.4.1835
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\SQLitePCLRaw.batteries_v2.dll
----------------------------------------
SQLitePCLRaw.provider.e_sqlite3
    Assembly Version: 2.1.4.1835
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\SQLitePCLRaw.provider.e_sqlite3.dll
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Assembly Version: 7.0.11.0
    Location: C:\Users\harry\OneDrive\Documents\aa-tools-dogshit\AAEmu-Tools-v0.4.1\AAEmu-Tools\AAEmu.DBEditor\Microsoft.EntityFrameworkCore.Sqlite.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Overlapped.dll
----------------------------------------

************** JIT Debugging **************


```

Please let me know if there is anything else I Can provide to assist :)

**Comment by ZeromusXYZ** [comment]
I actually know this is a thing, just never bothered to fix it since the tool isn't finished yet anyway 😏
It will be addressed on my next update.

**Comment by ZeromusXYZ** [comment]
This has been fixed in my most recent commit to the ``develop`` branch
https://github.com/ZeromusXYZ/AAEmu-Tools/commit/d3821da8abaecdd2ad794abb0195089b3ac8b2de
